export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"
plugins=(git vi-mode zsh-syntax-highlighting)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
source $ZSH/oh-my-zsh.sh
source ~/.bash_profile


# Configure history
setopt appendhistory
setopt sharehistory
setopt incappendhistory

if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='mvim'
fi

