export ZSH=~/.oh-my-zsh

ZSH_THEME="lambda"

plugins=(vi-mode)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
source $ZSH/oh-my-zsh.sh
source ~/.bash_profile

setopt PROMPT_SUBST


setopt hist_ignore_all_dups inc_append_history
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

